// DEMO

export const GET_DEMOS = "GET_DEMOS";
export const GET_DEMO = "GET_DEMO";
export const CREATE_DEMO = "CREATE_DEMO";
export const UPDATE_DEMO = "UPDATE_DEMO";
export const DELETE_DEMO = "DELETE_DEMO";

// AUTH

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// APPOINTMENTS

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

// DOCTORS

export const GET_DOCTORS = "GET_DOCTORS";
export const GET_DOCTOR = "GET_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

//EMPLOYEES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";

// EXAMINATIONS

export const GET_EXAMINATIONS = "GET_EXAMINATIONS";
export const GET_EXAMINATION = "GET_EXAMINATION";
export const CREATE_EXAMINATION = "CREATE_EXAMINATION";
export const UPDATE_EXAMINATION = "UPDATE_EXAMINATION";
export const DELETE_EXAMINATION = "DELETE_EXAMINATION";

// RECORDS

export const GET_RECORDS = "GET_RECORDS";
export const GET_RECORD = "GET_RECORD";
export const CREATE_RECORD = "CREATE_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";
export const UPDATE_VACCINE = "UPDATE_VACCINE";
export const UPDATE_ALERGEN = "UPDATE_ALERGEN";

// PATIENTS

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";
export const CREATE_PATIENTS_VISITS = "CREATE_PATIENTS_VISITS";
export const DELETE_FILTERED_PATIENT = "DELETE_FILTERED_PATIENT";

// DEPARTMENTS

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

// HOSPITALS

export const GET_HOSPITALS = "GET_HOSPITALS";
export const GET_HOSPITAL = "GET_HOSPITAL";
export const CREATE_HOSPITAL = "CREATE_HOSPITAL";
export const UPDATE_HOSPITAL = "UPDATE_HOSPITAL";
export const DELETE_HOSPITAL = "DELETE_HOSPITAL";

// DISEASES

export const GET_DISEASES = "GET_DISEASES";
export const GET_DISEASE = "GET_DISEASE";
export const CREATE_DISEASE = "CREATE_DISEASE";
export const UPDATE_DISEASE = "UPDATE_DISEASE";
export const DELETE_DISEASE = "DELETE_DISEASE";

// REFERRALS

export const GET_REFERRALS = "GET_REFERRALS";
export const GET_REFERRAL = "GET_REFERRAL";
export const CREATE_REFERRAL = "CREATE_REFERRAL";
export const UPDATE_REFERRAL = "UPDATE_REFERRAL";
export const DELETE_REFERRAL = "DELETE_REFERRAL";

// ADMISSIONS

export const GET_ADMISSIONS = "GET_ADMISSIONS";
export const GET_ADMISSION = "GET_ADMISSION";
export const CREATE_ADMISSION = "CREATE_ADMISSION";
export const UPDATE_ADMISSION = "UPDATE_ADMISSION";
export const DELETE_ADMISSION = "DELETE_ADMISSION";

// STATES

export const GET_STATES = "GET_STATES";
export const GET_STATE = "GET_STATE";
export const CREATE_STATE = "CREATE_STATE";
export const UPDATE_STATE = "UPDATE_STATE";
export const DELETE_STATE = "DELETE_STATE";

// MEDICAL_REPORTS

export const GET_MEDICAL_REPORTS = "GET_MEDICAL_REPORTS";
export const GET_MEDICAL_REPORT = "GET_MEDICAL_REPORT";
export const CREATE_MEDICAL_REPORT = "CREATE_MEDICAL_REPORT";
export const UPDATE_MEDICAL_REPORT = "UPDATE_MEDICAL_REPORT";
export const DELETE_MEDICAL_REPORT = "DELETE_MEDICAL_REPORT";

// DISCHARGE LISTS

export const GET_DISCHARGE_LISTS = "GET_DISCHARGE_LISTS";
export const GET_DISCHARGE_LIST = "GET_DISCHARGE_LIST";
export const CREATE_DISCHARGE_LIST = "CREATE_DISCHARGE_LIST";
export const UPDATE_DISCHARGE_LIST = "UPDATE_DISCHARGE_LIST";
export const DELETE_DISCHARGE_LIST = "DELETE_DISCHARGE_LIST";

// ANALYSIS RESULTS

export const GET_ANALYSIS_RESULTS = "GET_ANALYSIS_RESULTS";
export const GET_ANALYSIS_RESULT = "GET_ANALYSIS_RESULT";
export const CREATE_ANALYSIS_RESULT = "CREATE_ANALYSIS_RESULT";
export const UPDATE_ANALYSIS_RESULT = "UPDATE_ANALYSIS_RESULT";
export const DELETE_ANALYSIS_RESULT = "DELETE_ANALYSIS_RESULT";

// LAB REPORTS

export const GET_LAB_REPORTS = "GET_LAB_REPORTS";
export const GET_LAB_REPORT = "GET_LAB_REPORT";
export const CREATE_LAB_REPORT = "CREATE_LAB_REPORT";
export const UPDATE_LAB_REPORT = "UPDATE_LAB_REPORT";
export const DELETE_LAB_REPORT = "DELETE_LAB_REPORT";
export const GET_NUMBER_OF_APPOINTMENTS = "GET_NUMBER_OF_APPOINTMENTS";

//LAB VISITS
export const GET_LAB_VISITS = "GET_LAB_VISITS";
export const UPDATE_LAB_VISITS = "UPDATE_LAB_VISITS";
export const CREATE_LAB_VISIT = "CREATE_LAB_VISIT";

//PATIENTS ADMISSIONS
export const GET_PATIENTS_ADMISSIONS = "GET_PATIENTS_ADMISSIONS";
export const UPDATE_PATIENT_ADMISSION = "UPDATE_PATIENT_ADMISSION";
export const CREATE_PATIENT_ADMISSION = "CREATE_PATIENT_ADMISSION";

//HOSPITAL ROOMS
export const GET_HOSPITAL_ROOMS = "GET_HOSPITAL_ROOMS";

//PATIENTS HISTORY
export const GET_PATIENTS_HISTORY = "GET_PATIENTS_HISTORY";
export const CREATE_PATIENT_HISTORY = " CREATE_PATIENT_HISTORY";
export const GET_PATIENTS_VISITS = "GET_PATIENTS_VISITS";
export const CREATE_PATIENT_VISITS = "CREATE_PATIENT_VISITS";
